# =============================================================================
# VM Outputs
# =============================================================================

output "ubuntu_vms" {
  description = "Map of Ubuntu VM information"
  value = {
    for name, vm in proxmox_virtual_environment_vm.ubuntu_vm : name => {
      vm_id = vm.vm_id
      name  = vm.name
      ip    = try(vm.ipv4_addresses[1][0], split("/", local.ubuntu_vms[name].ip)[0])
    }
  }
}

output "nixos_vms" {
  description = "Map of NixOS VM information"
  value = {
    for name, vm in proxmox_virtual_environment_vm.nixos_vm : name => {
      vm_id = vm.vm_id
      name  = vm.name
      ip    = try(vm.ipv4_addresses[1][0], split("/", local.nixos_vms[name].ip)[0])
    }
  }
}

output "all_vms" {
  description = "Combined map of all VMs"
  value = merge(
    {
      for name, vm in proxmox_virtual_environment_vm.ubuntu_vm : name => {
        vm_id = vm.vm_id
        name  = vm.name
        os    = "ubuntu"
        ip    = try(vm.ipv4_addresses[1][0], split("/", local.ubuntu_vms[name].ip)[0])
      }
    },
    {
      for name, vm in proxmox_virtual_environment_vm.nixos_vm : name => {
        vm_id = vm.vm_id
        name  = vm.name
        os    = "nixos"
        ip    = try(vm.ipv4_addresses[1][0], split("/", local.nixos_vms[name].ip)[0])
      }
    }
  )
}

# =============================================================================
# Colmena Helper
# =============================================================================

output "colmena_hosts" {
  description = "NixOS hosts for Colmena deployment"
  value = {
    for name, vm in proxmox_virtual_environment_vm.nixos_vm : name => {
      ip   = split("/", local.nixos_vms[name].ip)[0]
      tags = ["nixos", "docker"]
    }
  }
}

# =============================================================================
# DNS Configuration
# =============================================================================

output "unbound_config" {
  description = "Unbound DNS config for pfSense (copy to Services > DNS Resolver > Custom Options)"
  value = <<-EOT
# Generated by OpenTofu - paste into pfSense DNS Resolver Custom Options
# =============================================================================
# INFRASTRUCTURE (static)
# =============================================================================
# pfSense Router
local-zone: "pfsense.tap." static
local-data: "pfsense.tap. 3600 IN A 10.0.0.1"

# Pi-hole DNS
local-zone: "pihole.tap." static
local-data: "pihole.tap. 3600 IN A 10.0.0.18"

# Unraid NAS
local-zone: "tower.tap." static
local-data: "tower.tap. 3600 IN A 10.0.0.5"

# Proxmox Cluster
local-zone: "strongbad.tap." static
local-data: "strongbad.tap. 3600 IN A 10.0.0.10"

local-zone: "strongmad.tap." static
local-data: "strongmad.tap. 3600 IN A 10.0.0.11"

local-zone: "strongsad.tap." static
local-data: "strongsad.tap. 3600 IN A 10.0.0.12"

# =============================================================================
# NixOS VMs (Colmena-managed, Traefik reverse proxies)
# =============================================================================
%{for name, config in local.nixos_vms~}
%{if try(config.domain, "") != ""~}
local-zone: "${config.domain}." redirect
local-data: "${config.domain}. 3600 IN A ${split("/", config.ip)[0]}"

%{endif~}
%{endfor~}
# =============================================================================
# Ubuntu VMs (cloud-init provisioned)
# =============================================================================
%{for name, config in local.ubuntu_vms~}
%{if try(config.domain, "") != ""~}
local-zone: "${config.domain}." redirect
local-data: "${config.domain}. 3600 IN A ${split("/", config.ip)[0]}"

%{endif~}
%{endfor~}
  EOT
}
