# =============================================================================
# DNS Configuration (pfSense Unbound)
# =============================================================================
# Pushes DNS entries directly to pfSense DNS Resolver via config file.
# Requires pfSense Custom Options to include: include-toplevel: /var/unbound/conf.d/*

# ---------------------------------------------------------------------------
# Static infrastructure entries (derived from shared infra_devices)
# ---------------------------------------------------------------------------
locals {
  static_dns_entries = {
    for name, dev in local.infra_devices :
    "${name}.tap" => dev.ip
  }

  # VM entries use redirect zones for wildcard subdomain routing (*.arr.tap, etc.)
  vm_dns_entries = {
    for name, host in local.hosts_config.hosts :
    host.domain => host.ip
    if try(host.domain, "") != ""
  }
}

# ---------------------------------------------------------------------------
# Managed Unbound config file on pfSense
# ---------------------------------------------------------------------------
resource "pfsense_dnsresolver_configfile" "homelab_dns" {
  name = "tofu-managed"
  content = join("\n", concat(
    ["server:"],
    ["# Generated by OpenTofu — do not edit manually"],
    [""],
    ["# Infrastructure (static)"],
    [for domain, ip in local.static_dns_entries :
      "local-zone: \"${domain}.\" static\nlocal-data: \"${domain}. 3600 IN A ${ip}\""
    ],
    [""],
    ["# NixOS VMs (wildcard subdomains via redirect zones)"],
    [for domain, ip in local.vm_dns_entries :
      "local-zone: \"${domain}.\" redirect\nlocal-data: \"${domain}. 3600 IN A ${ip}\""
    ],
  ))
}
